version: "3"
virtualmachines:
- name: k8s
  image: ubuntu-os-cloud/ubuntu-2404-lts-amd64
  memory: 16384
  cpus: 4
  allow_external_ingress:
  - http
  - https
  - high-ports
aws_accounts:
- name: bedrock
  services:
  - bedrock
  regions:
  - us-east-1
  - us-east-2
  - us-west-2
  managed_policies:
  - arn:aws:iam::aws:policy/AmazonBedrockLimitedAccess
